### ISSUE TITLE
Unable to build with libphobos 2.081.0

### ISSUE THREAD

**Issue by Supatier** [GodotNativeTools/godot-d#37]
```
Performing "debug" build using dmd for x86_64.
godot-d 0.0.6: building configuration "library"...
/home/abc/.dub/packages/godot-d-0.0.6/godot-d/src/godot/core/variant.d(367,10): Error: function pointer Fn(godot_variant*, const(__c_long)) is not callable using argument types (godot_variant*, long*)
/home/abc/.dub/packages/godot-d-0.0.6/godot-d/src/godot/core/variant.d(367,10):        cannot pass argument cast(long*)&input of type long* to parameter const(__c_long)
/home/abc/.dub/packages/godot-d-0.0.6/godot-d/src/godot/core/array.d(158,22): Error: template instance `godot.core.variant.Variant.__ctor!(const(long))` error instantiating
/home/abc/.dub/packages/godot-d-0.0.6/godot-d/classes/godot/area.d(90,21):        instantiated from here: append!(const(long))
```
Using phobos `2.080.1` works. It's not a `dmd` issue.

**Comment by sheepandshepherd** [comment]
This was caused by a change to the `int64_t` alias in the v2.081.x versions. Apparently it was an unintended side effect of attempts to improve C++ interop, but the v2.082.0 beta [reverts the broken aliases](https://dlang.org/changelog/2.082.0.html#osx64_long_cppmangling), so this should be fixed once v2.082 is released.

**Comment by averagehat** [comment]
I am having the same problem on OS X with new versions of mdm /ldc
